### PR TITLE
added windows support

### PR DESCRIPTION
**Pull request by soapdog**
This PR adds a suitable batch file for windows and changes the code in `main.rkt` to handle it.

### CODE REVIEW

**Comment by nixin72** [comment]
Hey @soapdog, this is awesome! Thank you so much for contributing! I don't have a way to test this, do you think you could just include a screenshot of running the command in a comment? 

Thank you!

**Comment by spdegabrielle** [comment]
Thank you both for this.

I’m looking to do an official *launch* of the tool & templates in the next issue of https://racket-news.com/  that will come out on September 14th, and Windows support is essential!

**Comment by soapdog** [comment]
@nixin72 

image

Does this work?

**Comment by soapdog** [comment]
To be honest, I think that both the bash and windows script needs changing before going live. They don't check if the `git clone` operation was successful before attempting to delete `.git` and that can lead to problems.

**Comment by soapdog** [comment]
The windows batch file checks if the destination folder exists before entering it and deleting the `.git` folder. I suggest a similar modification is made to the bash version as well.

**Comment by nixin72** [comment]
That's a very good call - if this is called from within a git repo, then if it were to fail it would delete the .git directory, which would be very bad. I'll add the same error checking on Unix. Thank you so much.

**Comment by nixin72** [comment]
And thank you for the screenshot, that's perfect! Any last changes before it gets merged in?

**Comment by soapdog** [comment]
@nixin72 not from me. I think the windows version is good for a MVP. :-)

**Pull request merged**
