### PR TITLE
Add macosx support

### PR DESCRIPTION
**Pull request by spdegabrielle**
@nixin72 @soapdog seems to work 

@nixin72 can you update  https://pkgd.racket-lang.org/pkgn/package/from-template ?

I'd like to do a 'beta' release on racket slack, because something always comes up.

### CODE REVIEW

**Comment by nixin72** [comment]
The bash script for MacOS is the same as the one for Linux - how come you'd like to add a script specifically for mac?

**Comment by spdegabrielle** [comment]
Oops  - added I’m error- let me fix

**Comment by spdegabrielle** [comment]
@nixin72 the macOS version is correct - it differs by one line;

```
	git clone "https://github.com/racket-templates/$1.git" $2
```

**Comment by spdegabrielle** [comment]
Uses https

**Comment by nixin72** [comment]
Hmm, I think they should both use HTTPS actually. Cause the SSH one will rely on the user having an SSH key set up. But the two should be the same I think. I'll change the Linux one to use HTTPS instead of SSH.

**Comment by spdegabrielle** [comment]
in hindsight I'm surprised the linux version doesn't need the [`define-runtime-path`](https://docs.racket-lang.org/reference/Filesystem.html#%28form._%28%28lib._racket%2Fruntime-path..rkt%29._define-runtime-path%29%29)

The good think about a beta on slack is it will shake little things like this out.

**Comment by spdegabrielle** [comment]
@nixin72 is there any barrier to applying this PR?
(you may want to 'squash')

**Comment by soapdog** [comment]
Should I alter the windows version to use HTTPS as well?

**Comment by spdegabrielle** [comment]
Thank you @nixin72 Philip!

**Pull request merged**
