### PR TITLE
More instantiation options

### PR DESCRIPTION
**Pull request by nixin72**
Completely reworked the main file to allow interaction at command line with `-i` flag is supplied. 

I think this is cool because it also shows people who they can use the `command-line` tool from Racket to build CLI interfaces really easily. 

Still some more testing that needs to be done before this is ready to merge.

### CODE REVIEW

**Comment by nixin72** [comment]
Okay, I think this is ready now. You wanna take a look @spdegabrielle?

**Comment by spdegabrielle** [comment]
Sorry been busy. I’ll try it out this afternoon. TYVM for doing this!

S.

**Review by spdegabrielle — COMMENTED** [review]
## Comments

This is very good! 🥇 
You've done so much I feel guilty asking for more - but I'm going to anyway :grinning: :

I think we need to retain parts of the existing `info.rkt` file as there is some functionality in the from-template `info.rkt` file. I think appending should be sufficient but this may mean some small changes to `info.rkt` files in the template repos. Need to think about this some more and discuss on discord/slack if we get a chance.

e.g. creating a new `info.rkt` would break the from-template template because the `raco` command  functionality requires `(define raco-commands ...)` in `info.rkt`  - I think it will only affect the templates intended to be installed as packages: DrRacket plugin(in-progress), raco command extension and the assumptions of the `package` template.

To complicate things I'm keen that the template repos will still work if the users just click `Use this template` from the repo page in GitHub.  (new users sometimes struggle with adding the racket executables directory to their $PATH so they can use `raco`)

https://docs.racket-lang.org/pkg/metadata.html


image


```racket
(define raco-commands
  '(("from-template" "main.rkt" "Install a repo from a template at racket-templates" 50)))
```

## issues

Only one - while typing `raco new` without any other arguments triggered the '_need to supply a name of a template._ message, it also seems to have triggered the `Hmm, an unexpected error has occured...`

I'm sorry I haven't looked at the code to work out what was happening.

```bash
spdegabrielle@Miriams-MBP from-template % raco new
Need to supply a name of a template.
Checkout https://github.com/racket-templates for a list of available templates.


Hmm, an unexpected error has occured...
If you'd like, we'd really appreciate it if you filed a bug report at
https://github.com/nixin72/from-template/issues/new

Sorry for the inconvenience, please try again and change up your options if the problem persists.
```

**Comment by nixin72** [comment]
So I ran into an issue that I'm not sure what's going on. I've got the following code:
```
(define [exisiting-options-in-info-rkt]
  (define file-path (build-path (current-directory) (output-dir) "info.rtk"))
  (println file-path)
  (println (file-exists? file-path))
  (if (file-exists? file-path)
      (for/list ([line (file->lines file-path)])
        (define l (call-with-input-string
                   line
                   (lambda (in) (read in))))
        (second l))
      "fail"))
```

I'm trying to make a list of all of the values defined in the existing `info.rkt`, then simply replace the existing ones and append any new ones. This will fulfill the goal of not deleting any important information, while also keeping the templates available to just clone as a GitHub template. 

However, for some reason this always says the file doesn't exist. I'm unsure why this is, because I'm running this function just to test it as the very last thing I do in the file, so the `info.rtk` file *should* exist in the repo that just got cloned. If I open up a Racket REPL and run the exact same code:
```
(file-exists? (build-path (current-directory) "output-dir" "info.rkt"))
```
It spits out `#t`, as I would expect. So how come it's false when running the whole file? :confused:

**Comment by spdegabrielle** [comment]
> I'm trying to make a list of all of the values defined in the existing info.rkt, then simply replace the existing ones and append any new ones

That is a much better approach than my append suggestion 

> However, for some reason this always says the file doesn't exist. 

I’m only guessing but try inserting a 5 second pause in case the code is faster than the disk?

**Comment by nixin72** [comment]
Nope, adding a sleep doesn't change anything...

**Review by spdegabrielle — COMMENTED** [review]
Hi

I just found https://docs.racket-lang.org/raco/getinfo.html?q=Get-info%20#%28def._%28%28lib._setup%2Fgetinfo..rkt%29._get-info%29%29 don’t know if it is helpful

**Comment by nixin72** [comment]
Okay, so close now... Just need to figure out how to convert this:
```
(define scribblings (quote (("scribblings/guiapp.scrbl" ()))))
(define build-deps (quote ("scribble-lib" "racket-doc" "rackunit-lib")))
(define git-repository "\"\"")
(define pkg-authors (list ""))
(define version "1.0.0")
(define license "MIT")
(define collection "test0")
(define pkg-desc "\"\"")
(define entry-point "main.rkt")
(define deps (quote ("base")))
```
to
```
(define scribblings '(("scribblings/guiapp.scrbl" ())))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define git-repository "\"\"")
(define pkg-authors '(""))
(define version "1.0.0")
(define license "MIT")
(define collection "test0")
(define pkg-desc "\"\"")
(define entry-point "main.rkt")
(define deps ("base"))
```
So just turning all the `(quote (...))` into `'(...)` basically.

**Comment by nixin72** [comment]
Okay @spdegabrielle, pretty sure this is working now and ready for testing!

**Comment by spdegabrielle** [comment]
Awesome I'll give it a go !

**Comment by nixin72** [comment]
Okay, I've tested a bit more and not found issues so far, so I'm gonna go ahead and merge this in.

**Comment by spdegabrielle** [comment]
thank you

**Pull request merged**
